apiVersion: v1
kind: Service
metadata:
  name: {{ include "court-service.fullname" . }}
  labels:
    {{- include "court-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "court-service.selectorLabels" . | nindent 4 }}
